# Read The Docs config
# - https://docs.readthedocs.io/en/latest/config-file/v2.html
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-23.11"

# Build documentation with Sphinx
sphinx:
  builder: html
  configuration: docs/source/conf.py

conda:
  environment: environment.yml
